### PR TITLE
Upstream fixes

### LINKED ISSUE #446: Make player_rank a composite key to be able to support multiple group rankings
Make player_rank a composite key to be able to support multiple group rankings. This will allow us to store rankings based on academic/non-academic, offense and defense groups.

### LINKED ISSUE #673: Allow icmp ping towards private instances
The latest firewall changes dont allow icmp ping towards private instances, we need to fix that

### LINKED ISSUE #677: Make the "Delete All" button use POST instead
image

image

### PR DESCRIPTION
**Pull request by proditis**
The following PR brings changes that help in setting up CTF events

The list changes includes:
* [x] fixes #677
* [x] fixes #446
* [x] Makes utf8mb4 default throughout our schema files
* [x] Introduce an instances PF only action
* [x] fixes #673

### CODE REVIEW

File: schemas/echoCTF-routines.sql [hunk 1]
```diff
@@ -289,7 +291,11 @@ END ;;
...
-  call populate_memcache();
-  call calculate_ranks();
-  call calculate_country_rank();
+    IF (SELECT val FROM sysconfig WHERE id='time_zone') IS NOT NULL THEN
+      SET GLOBAL time_zone=(SELECT val FROM sysconfig WHERE id='time_zone');
+    END IF;
+    call populate_memcache();
+    call calculate_ranks();
+    call calculate_country_rank();
+--    call calculate_team_ranks();
```
Comment (proditis) [inline schemas/echoCTF-routines.sql:300]: remove comment
```suggestion
    call calculate_team_ranks();
```

File: frontend/widgets/stream/StreamWidget.php [hunk 2]
```diff
@@ -43,14 +43,22 @@ public function init()
 
     private function configureDataProvider()
     {
-      $model=\app\models\Stream::find()->select('stream.*,TS_AGO(stream.ts) as ts_ago');
+      $model=\app\models\Stream::find()->select('stream.*,TS_AGO(stream.ts) as ts_ago')->joinWith(['player']);
+      if(\Yii::$app->user->isGuest)
+      {
+        $model->andWhere(['academic'=>1]);
```
Comment (proditis) [inline frontend/widgets/stream/StreamWidget.php:49]:
```suggestion
        $model->andWhere(['academic'=>0]);
```

File: backend/modules/frontend/models/PlayerAR.php [hunk 3]
```diff
@@ -88,17 +100,16 @@ public function rules()
     {
         return [
             [['username', 'type', 'status'], 'required'],
-            [['verification_token','password_reset_token'], 'string'],
-            [['verification_token','password_reset_token'], 'default','value'=>null],
             [['type'], 'string'],
             [['active', 'status'], 'integer'],
-            [['academic'], 'boolean'],
+            [['academic'], 'integer'],
```
Comment (proditis) [inline backend/modules/frontend/models/PlayerAR.php:105]:
```suggestion
            [['academic'], 'integer'],
            [['academic'], 'default','value'=>0],
```

File: frontend/controllers/SiteController.php [hunk 4]
```diff
@@ -24,11 +24,33 @@ class SiteController extends \app\components\BaseController
...
     public function behaviors()
     {
-        return ArrayHelper::merge(parent::behaviors(),[
+        $parent=parent::behaviors();
+        unset($parent['access']['rules']['teamsAccess']);
+        return ArrayHelper::merge($parent,[
             'access' => [
                 'class' => AccessControl::class,
-                'only' => ['login','logout', 'changelog', 'register', 'request-password-reset', 'verify-email', 'resend-verification-email', 'changelog', 'captcha'],
+                'only' => ['index','login','logout',  'register', 'request-password-reset', 'verify-email', 'resend-verification-email',  'captcha'],
```
Comment (proditis) [inline frontend/controllers/SiteController.php:32]:
```suggestion
                'only' => ['index','login','logout', 'changelog', 'register', 'request-password-reset', 'verify-email', 'resend-verification-email',  'captcha'],
```

File: frontend/modules/subscription/Module.php [hunk 5]
```diff
@@ -67,6 +66,7 @@ public function getExpires()
 
     public function getIsActive()
     {
+      return true;
```
Comment (proditis) [inline frontend/modules/subscription/Module.php:69]:
```suggestion
```

File: frontend/modules/target/models/Target.php [hunk 6]
```diff
@@ -128,9 +128,9 @@ public function getSpinDenied()
       {
         return true;
       }
-
-      if(Yii::$app->user->identity->profile->last->vpn_local_address === null && intval(self::find()->player_progress(Yii::$app->user->id)->where(['t.id'=>$this->id])->one()->player_findings)<1 && intval(self::find()->player_progress(Yii::$app->user->id)->where(['t.id'=>$this->id])->one()->player_treasures)<1)
-        return true;
+// dont check for progress
+//      if(Yii::$app->user->identity->profile->last->vpn_local_address === null && intval(self::find()->player_progress(Yii::$app->user->id)->where(['t.id'=>$this->id])->one()->player_findings)<1 && intval(self::find()->player_progress(Yii::$app->user->id)->where(['t.id'=>$this->id])->one()->player_treasures)<1)
+//        return true;
```
Comment (proditis) [inline frontend/modules/target/models/Target.php:133]:
```suggestion
      if(Yii::$app->user->identity->profile->last->vpn_local_address === null && intval(self::find()->player_progress(Yii::$app->user->id)->where(['t.id'=>$this->id])->one()->player_findings)<1 && intval(self::find()->player_progress(Yii::$app->user->id)->where(['t.id'=>$this->id])->one()->player_treasures)<1)
        return true;
```

**Review by proditis — COMMENTED** [review]
needs testing

File: frontend/controllers/DashboardController.php [hunk 7]
```diff
@@ -56,21 +59,21 @@ public function actionIndex()
     {
       $dashboardStats=new \stdClass();
       $dashboardStats->countries=(int) Profile::find()->select(['country'])->distinct()->count();
-      $dashboardStats->claims=(int) PlayerTreasure::find()->count();
+      $dashboardStats->claims=(int) PlayerTreasure::find()->where(['player.academic'=>Yii::$app->user->identity->academic])->joinWith(['player'])->count();
       $rows = (new \yii\db\Query())
-        ->select(['date_format(ts,"%D") as dat', 'count(*) as cnt','sum(if(player_id in ('.Yii::$app->user->id.'),1,0)) as pcnt'])
+        ->select(['TIMESTAMPDIFF(HOUR, ts, now()) as dat', 'count(*) as cnt','sum(if(player_id in ('.Yii::$app->user->id.'),1,0)) as pcnt'])
```
Comment (proditis) [inline frontend/controllers/DashboardController.php:64]:
```suggestion
->select(['date_format(ts,"%D") as dat', 'count(*) as cnt','sum(if(player_id in ('.Yii::$app->user->id.'),1,0)) as pcnt'])
```

File: frontend/controllers/DashboardController.php [hunk 8]
```diff
@@ -56,21 +59,21 @@ public function actionIndex()
...
       $dashboardStats=new \stdClass();
       $dashboardStats->countries=(int) Profile::find()->select(['country'])->distinct()->count();
-      $dashboardStats->claims=(int) PlayerTreasure::find()->count();
+      $dashboardStats->claims=(int) PlayerTreasure::find()->where(['player.academic'=>Yii::$app->user->identity->academic])->joinWith(['player'])->count();
       $rows = (new \yii\db\Query())
-        ->select(['date_format(ts,"%D") as dat', 'count(*) as cnt','sum(if(player_id in ('.Yii::$app->user->id.'),1,0)) as pcnt'])
+->select(['date_format(ts,"%D") as dat', 'count(*) as cnt','sum(if(player_id in ('.Yii::$app->user->id.'),1,0)) as pcnt'])
         ->from('stream')
-        ->where(['>=','ts', new \yii\db\Expression('now()-interval 10 day')])
+        ->where(['>=','ts', new \yii\db\Expression('now()-interval 48 HOUR')])
```
Comment (proditis) [inline frontend/controllers/DashboardController.php:66]:
```suggestion
        ->where(['>=','ts', new \yii\db\Expression('now()-interval 10 day')])
```

File: backend/commands/CronController.php [hunk 9]
```diff
@@ -198,32 +236,40 @@ public function actionInstances()
...
+                }
+                $dc->pull();
+                $dc->spin();
               }
-              $dc->pull();
-              $dc->spin();
               if($val->player->last->vpn_local_address!==null)
               {
-                Pf::add_table_ip($dc->name.'_clients',long2ip($val->player->last->vpn_local_address));
+                Pf::add_table_ip($dc->name.'_clients',long2ip($val->player->last->vpn_local_address),true);
```
Comment (proditis) [inline backend/commands/CronController.php:251]:
```suggestion
                Pf::add_table_ip($dc->name.'_clients',long2ip($val->player->last->vpn_local_address)/*,true*/);
```
